sudo: required

language: node_js

cache:
  directories:
    - node_modules

node_js:
  - "12"

script:
  - echo "npm test temporarily disabled"

install:
  - npm install
  - bash .travis/build.sh || true
  - ls build || true

deploy:
  - provider: gcs
    access_key_id: $GCS_ACCESS_KEY_ID
    secret_access_key: $GCS_SECRET_KEY_ID
    bucket: dev-dmm-info.knstats.com
    skip_cleanup: true
    local-dir: build
    cache_control: "no-cache"
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^develop$
  - provider: gcs
    access_key_id: $GCS_ACCESS_KEY_ID
    secret_access_key: $GCS_SECRET_KEY_ID
    bucket: staging-dmm-info.knstats.com
    skip_cleanup: true
    local-dir: build
    cache_control: "no-cache"
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^staging$

  - provider: gcs
    access_key_id: $GCS_ACCESS_KEY_ID_PROD
    secret_access_key: $GCS_SECRET_KEY_ID_PROD
    bucket: info.dmm.exchange
    skip_cleanup: true
    local-dir: build
    cache_control: "public, max-age=900"
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^main$
