sudo: required

language: node_js

cache:
    directories:
      - node_modules

node_js:
  - "12"

script:
  - echo "npm test temporarily disabled"

install:
  - npm install
  - CI=false npm run build

deploy:
  - provider: gcs
    access_key_id: $GCS_ACCESS_KEY_ID
    secret_access_key: $GCS_SECRET_KEY_ID
    bucket: dev-dmm-info.knstats.com
    skip_cleanup: true
    local-dir: build
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^develop$
